/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package open.trading.data;

import java.util.*;

public class StockData {
    public boolean getStockCandles(List<String> symbols) {
        return true;
    }
}
